"""
Fix: Remove ScrollView from iOSNewTaskSheet and iOSEditTaskSheet.
Replace with Form-based layout using native iOS sections.
Date picker changes from .graphical to .compact to avoid large calendar grid.
"""
import sys

home_path  = "/Users/noahmcclung/Development/Apple/Softwares/OneFocus/OneFocus/Views/iOS/Tabs/iOSHomeView.swift"
tasks_path = "/Users/noahmcclung/Development/Apple/Softwares/OneFocus/OneFocus/Views/iOS/Tabs/iOSTasksView.swift"

with open(home_path) as f:  home  = f.read()
with open(tasks_path) as f: tasks = f.read()

# ─────────────────────────────────────────────────────────────────────────────
# iOSNewTaskSheet  (iOSHomeView.swift)
# Replace the entire body from NavigationStack { ScrollView { ... } } with
# a Form-based layout.
# ─────────────────────────────────────────────────────────────────────────────

OLD_NEW_BODY = (
    "    var body: some View {\n"
    "        NavigationStack {\n"
    "            ScrollView {\n"
    "                VStack(spacing: AppConstants.Spacing.xl) {\n"
    "                    // Title\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Label(\"Task Title\", systemImage: \"pencil\")\n"
    "                            .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                            .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        TextField(\"Enter task title\", text: $taskTitle)\n"
    "                            .font(.system(size: AppConstants.FontSize.body))\n"
    "                            .padding(AppConstants.Spacing.md)\n"
    "                            .background(AppConstants.Colors.inputBackground)\n"
    "                            .cornerRadius(AppConstants.CornerRadius.medium)\n"
    "                    }\n"
    "                    // Category (Pro only)\n"
    "                    if proAccess.isProUser {\n"
    "                        VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                            Label(\"Category\", systemImage: \"folder\")\n"
    "                                .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                                .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                            ScrollView(.horizontal, showsIndicators: false) {\n"
    "                                HStack(spacing: AppConstants.Spacing.sm) {\n"
    "                                    iOSCategoryChip(\n"
    "                                        icon: \"tray.fill\",\n"
    "                                        name: \"None\",\n"
    "                                        color: AppConstants.Colors.textSecondary,\n"
    "                                        isSelected: selectedCategoryID == nil\n"
    "                                    ) { selectedCategoryID = nil }\n"
    "                                    ForEach(taskCategoryManager.categories) { cat in\n"
    "                                        iOSCategoryChip(\n"
    "                                            icon: cat.icon,\n"
    "                                            name: cat.name,\n"
    "                                            color: cat.color,\n"
    "                                            isSelected: selectedCategoryID == cat.id\n"
    "                                        ) { selectedCategoryID = cat.id }\n"
    "                                    }\n"
    "                                }\n"
    "                                .padding(.vertical, 2)\n"
    "                            }\n"
    "                        }\n"
    "                    }\n"
    "                    // Priority\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Label(\"Priority\", systemImage: \"flag\")\n"
    "                            .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                            .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        Picker(\"Priority\", selection: $selectedPriority) {\n"
    "                            ForEach(Task.Priority.allCases, id: \\.self) { p in\n"
    "                                Text(p.rawValue).tag(p)\n"
    "                            }\n"
    "                        }\n"
    "                        .pickerStyle(.segmented)\n"
    "                    }\n"
    "                    // Due Date\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Toggle(isOn: $hasDueDate) {\n"
    "                            Label(\"Due Date\", systemImage: \"calendar\")\n"
    "                                .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                                .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        }\n"
    "                        .tint(AppConstants.Colors.primaryAccent)\n"
    "                        if hasDueDate {\n"
    "                            DatePicker(\"\", selection: $dueDate, displayedComponents: [.date])\n"
    "                                .datePickerStyle(.graphical)\n"
    "                                .labelsHidden()\n"
    "                        }\n"
    "                    }\n"
    "                    // Notes\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Label(\"Notes (Optional)\", systemImage: \"note.text\")\n"
    "                            .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                            .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        TextEditor(text: $notes)\n"
    "                            .font(.system(size: AppConstants.FontSize.body))\n"
    "                            .frame(minHeight: 90)\n"
    "                            .padding(AppConstants.Spacing.sm)\n"
    "                            .background(AppConstants.Colors.inputBackground)\n"
    "                            .cornerRadius(AppConstants.CornerRadius.medium)\n"
    "                            .scrollContentBackground(.hidden)\n"
    "                    }\n"
    "                    // Create button\n"
    "                    Button {\n"
    "                        let trimmedTitle = taskTitle.trimmingCharacters(in: .whitespaces)\n"
    "                        let trimmedNotes = notes.trimmingCharacters(in: .whitespaces)\n"
    "                        let newTask = Task(\n"
    "                            title:      trimmedTitle,\n"
    "                            dueDate:    hasDueDate ? dueDate : nil,\n"
    "                            priority:   selectedPriority,\n"
    "                            notes:      trimmedNotes.isEmpty ? nil : trimmedNotes,\n"
    "                            categoryID: selectedCategoryID\n"
    "                        )\n"
    "                        viewModel.addTask(newTask)\n"
    "                        dismiss()\n"
    "                    } label: {\n"
    "                        Text(\"Create Task\")\n"
    "                            .font(.system(size: AppConstants.FontSize.body, weight: .semibold))\n"
    "                            .foregroundColor(.white)\n"
    "                            .frame(maxWidth: .infinity)\n"
    "                            .padding(.vertical, 15)\n"
    "                            .background(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty\n"
    "                                        ? AppConstants.Colors.textTertiary\n"
    "                                        : AppConstants.Colors.primaryAccent)\n"
    "                            .cornerRadius(AppConstants.CornerRadius.medium)\n"
    "                    }\n"
    "                    .disabled(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty)\n"
    "                }\n"
    "                .padding(AppConstants.Spacing.xl)\n"
    "            }\n"
    "            .background(AppConstants.Colors.backgroundPrimary.ignoresSafeArea())\n"
    "            .navigationTitle(\"New Task\")\n"
    "            .navigationBarTitleDisplayMode(.inline)\n"
    "            .toolbar {\n"
    "                ToolbarItem(placement: .cancellationAction) {\n"
    "                    Button(\"Cancel\") { dismiss() }\n"
    "                        .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}"
)

NEW_NEW_BODY = (
    "    var body: some View {\n"
    "        NavigationStack {\n"
    "            Form {\n"
    "                // Title\n"
    "                Section {\n"
    "                    TextField(\"Task title\", text: $taskTitle)\n"
    "                        .font(.system(size: AppConstants.FontSize.body))\n"
    "                } header: {\n"
    "                    Text(\"Title\")\n"
    "                }\n"
    "\n"
    "                // Category (Pro only)\n"
    "                if proAccess.isProUser {\n"
    "                    Section {\n"
    "                        ScrollView(.horizontal, showsIndicators: false) {\n"
    "                            HStack(spacing: AppConstants.Spacing.sm) {\n"
    "                                iOSCategoryChip(\n"
    "                                    icon: \"tray.fill\",\n"
    "                                    name: \"None\",\n"
    "                                    color: AppConstants.Colors.textSecondary,\n"
    "                                    isSelected: selectedCategoryID == nil\n"
    "                                ) { selectedCategoryID = nil }\n"
    "                                ForEach(taskCategoryManager.categories) { cat in\n"
    "                                    iOSCategoryChip(\n"
    "                                        icon: cat.icon,\n"
    "                                        name: cat.name,\n"
    "                                        color: cat.color,\n"
    "                                        isSelected: selectedCategoryID == cat.id\n"
    "                                    ) { selectedCategoryID = cat.id }\n"
    "                                }\n"
    "                            }\n"
    "                            .padding(.vertical, 4)\n"
    "                        }\n"
    "                    } header: {\n"
    "                        Text(\"Category\")\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                // Priority\n"
    "                Section {\n"
    "                    Picker(\"Priority\", selection: $selectedPriority) {\n"
    "                        ForEach(Task.Priority.allCases, id: \\.self) { p in\n"
    "                            Text(p.rawValue).tag(p)\n"
    "                        }\n"
    "                    }\n"
    "                    .pickerStyle(.segmented)\n"
    "                } header: {\n"
    "                    Text(\"Priority\")\n"
    "                }\n"
    "\n"
    "                // Due Date\n"
    "                Section {\n"
    "                    Toggle(\"Set Due Date\", isOn: $hasDueDate)\n"
    "                        .tint(AppConstants.Colors.primaryAccent)\n"
    "                    if hasDueDate {\n"
    "                        DatePicker(\"Date\", selection: $dueDate, displayedComponents: [.date])\n"
    "                            .datePickerStyle(.compact)\n"
    "                    }\n"
    "                } header: {\n"
    "                    Text(\"Due Date\")\n"
    "                }\n"
    "\n"
    "                // Notes\n"
    "                Section {\n"
    "                    TextEditor(text: $notes)\n"
    "                        .font(.system(size: AppConstants.FontSize.body))\n"
    "                        .frame(minHeight: 80)\n"
    "                        .scrollContentBackground(.hidden)\n"
    "                } header: {\n"
    "                    Text(\"Notes (Optional)\")\n"
    "                }\n"
    "            }\n"
    "            .navigationTitle(\"New Task\")\n"
    "            .navigationBarTitleDisplayMode(.inline)\n"
    "            .toolbar {\n"
    "                ToolbarItem(placement: .cancellationAction) {\n"
    "                    Button(\"Cancel\") { dismiss() }\n"
    "                        .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                }\n"
    "                ToolbarItem(placement: .confirmationAction) {\n"
    "                    Button(\"Create\") {\n"
    "                        let trimmedTitle = taskTitle.trimmingCharacters(in: .whitespaces)\n"
    "                        let trimmedNotes = notes.trimmingCharacters(in: .whitespaces)\n"
    "                        let newTask = Task(\n"
    "                            title:      trimmedTitle,\n"
    "                            dueDate:    hasDueDate ? dueDate : nil,\n"
    "                            priority:   selectedPriority,\n"
    "                            notes:      trimmedNotes.isEmpty ? nil : trimmedNotes,\n"
    "                            categoryID: selectedCategoryID\n"
    "                        )\n"
    "                        viewModel.addTask(newTask)\n"
    "                        dismiss()\n"
    "                    }\n"
    "                    .fontWeight(.semibold)\n"
    "                    .foregroundColor(AppConstants.Colors.primaryAccent)\n"
    "                    .disabled(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty)\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}"
)

ok_new = OLD_NEW_BODY in home
print(f"iOSNewTaskSheet body found: {ok_new}")
if ok_new:
    home = home.replace(OLD_NEW_BODY, NEW_NEW_BODY)
    with open(home_path, "w") as f:
        f.write(home)
    print("iOSNewTaskSheet: OK")
else:
    # Debug: show what's around the ScrollView in the new task sheet
    idx = home.find("struct iOSNewTaskSheet")
    print(repr(home[idx:idx+200]))
    sys.exit(1)

# ─────────────────────────────────────────────────────────────────────────────
# iOSEditTaskSheet  (iOSTasksView.swift)
# ─────────────────────────────────────────────────────────────────────────────

OLD_EDIT_BODY = (
    "    var body: some View {\n"
    "        NavigationStack {\n"
    "            ScrollView {\n"
    "                VStack(spacing: AppConstants.Spacing.xl) {\n"
    "                    // Title\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Label(\"Task Title\", systemImage: \"pencil\")\n"
    "                            .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                            .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        TextField(\"Enter task title\", text: $taskTitle)\n"
    "                            .font(.system(size: AppConstants.FontSize.body))\n"
    "                            .padding(AppConstants.Spacing.md)\n"
    "                            .background(AppConstants.Colors.inputBackground)\n"
    "                            .cornerRadius(AppConstants.CornerRadius.medium)\n"
    "                    }\n"
    "                    // Category (Pro only)\n"
    "                    if proAccess.isProUser {\n"
    "                        VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                            Label(\"Category\", systemImage: \"folder\")\n"
    "                                .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                                .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                            ScrollView(.horizontal, showsIndicators: false) {\n"
    "                                HStack(spacing: AppConstants.Spacing.sm) {\n"
    "                                    iOSCategoryChip(\n"
    "                                        icon: \"tray.fill\",\n"
    "                                        name: \"None\",\n"
    "                                        color: AppConstants.Colors.textSecondary,\n"
    "                                        isSelected: selectedCategoryID == nil\n"
    "                                    ) { selectedCategoryID = nil }\n"
    "                                    ForEach(taskCategoryManager.categories) { cat in\n"
    "                                        iOSCategoryChip(\n"
    "                                            icon: cat.icon,\n"
    "                                            name: cat.name,\n"
    "                                            color: cat.color,\n"
    "                                            isSelected: selectedCategoryID == cat.id\n"
    "                                        ) { selectedCategoryID = cat.id }\n"
    "                                    }\n"
    "                                }\n"
    "                                .padding(.vertical, 2)\n"
    "                            }\n"
    "                        }\n"
    "                    }\n"
    "                    // Priority\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Label(\"Priority\", systemImage: \"flag\")\n"
    "                            .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                            .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        Picker(\"Priority\", selection: $selectedPriority) {\n"
    "                            ForEach(Task.Priority.allCases, id: \\.self) { p in\n"
    "                                Text(p.rawValue).tag(p)\n"
    "                            }\n"
    "                        }\n"
    "                        .pickerStyle(.segmented)\n"
    "                    }\n"
    "                    // Due Date\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Toggle(isOn: $hasDueDate) {\n"
    "                            Label(\"Due Date\", systemImage: \"calendar\")\n"
    "                                .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                                .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        }\n"
    "                        .tint(AppConstants.Colors.primaryAccent)\n"
    "                        if hasDueDate {\n"
    "                            DatePicker(\"\", selection: $dueDate, displayedComponents: [.date])\n"
    "                                .datePickerStyle(.graphical)\n"
    "                                .labelsHidden()\n"
    "                        }\n"
    "                    }\n"
    "                    // Notes\n"
    "                    VStack(alignment: .leading, spacing: AppConstants.Spacing.sm) {\n"
    "                        Label(\"Notes (Optional)\", systemImage: \"note.text\")\n"
    "                            .font(.system(size: AppConstants.FontSize.subheadline, weight: .medium))\n"
    "                            .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                        TextEditor(text: $notes)\n"
    "                            .font(.system(size: AppConstants.FontSize.body))\n"
    "                            .frame(minHeight: 90)\n"
    "                            .padding(AppConstants.Spacing.sm)\n"
    "                            .background(AppConstants.Colors.inputBackground)\n"
    "                            .cornerRadius(AppConstants.CornerRadius.medium)\n"
    "                            .scrollContentBackground(.hidden)\n"
    "                    }\n"
    "                    // Save button\n"
    "                    Button {\n"
    "                        let trimmedTitle = taskTitle.trimmingCharacters(in: .whitespaces)\n"
    "                        let trimmedNotes = notes.trimmingCharacters(in: .whitespaces)\n"
    "                        var updated = task\n"
    "                        updated.title      = trimmedTitle\n"
    "                        updated.priority   = selectedPriority\n"
    "                        updated.dueDate    = hasDueDate ? dueDate : nil\n"
    "                        updated.notes      = trimmedNotes.isEmpty ? nil : trimmedNotes\n"
    "                        updated.categoryID = selectedCategoryID\n"
    "                        viewModel.updateTask(updated)\n"
    "                        dismiss()\n"
    "                    } label: {\n"
    "                        Text(\"Save Changes\")\n"
    "                            .font(.system(size: AppConstants.FontSize.body, weight: .semibold))\n"
    "                            .foregroundColor(.white)\n"
    "                            .frame(maxWidth: .infinity)\n"
    "                            .padding(.vertical, 15)\n"
    "                            .background(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty\n"
    "                                        ? AppConstants.Colors.textTertiary\n"
    "                                        : AppConstants.Colors.primaryAccent)\n"
    "                            .cornerRadius(AppConstants.CornerRadius.medium)\n"
    "                    }\n"
    "                    .disabled(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty)\n"
    "                }\n"
    "                .padding(AppConstants.Spacing.xl)\n"
    "            }\n"
    "            .background(AppConstants.Colors.backgroundPrimary.ignoresSafeArea())\n"
    "            .navigationTitle(\"Edit Task\")\n"
    "            .navigationBarTitleDisplayMode(.inline)\n"
    "            .toolbar {\n"
    "                ToolbarItem(placement: .cancellationAction) {\n"
    "                    Button(\"Cancel\") { dismiss() }\n"
    "                        .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                }\n"
    "                ToolbarItem(placement: .confirmationAction) {\n"
    "                    Button(\"Save\") {\n"
    "                        let trimmedTitle = taskTitle.trimmingCharacters(in: .whitespaces)\n"
    "                        let trimmedNotes = notes.trimmingCharacters(in: .whitespaces)\n"
    "                        var updated = task\n"
    "                        updated.title      = trimmedTitle\n"
    "                        updated.priority   = selectedPriority\n"
    "                        updated.dueDate    = hasDueDate ? dueDate : nil\n"
    "                        updated.notes      = trimmedNotes.isEmpty ? nil : trimmedNotes\n"
    "                        updated.categoryID = selectedCategoryID\n"
    "                        viewModel.updateTask(updated)\n"
    "                        dismiss()\n"
    "                    }\n"
    "                    .fontWeight(.semibold)\n"
    "                    .foregroundColor(AppConstants.Colors.primaryAccent)\n"
    "                    .disabled(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty)\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}"
)

NEW_EDIT_BODY = (
    "    var body: some View {\n"
    "        NavigationStack {\n"
    "            Form {\n"
    "                // Title\n"
    "                Section {\n"
    "                    TextField(\"Task title\", text: $taskTitle)\n"
    "                        .font(.system(size: AppConstants.FontSize.body))\n"
    "                } header: {\n"
    "                    Text(\"Title\")\n"
    "                }\n"
    "\n"
    "                // Category (Pro only)\n"
    "                if proAccess.isProUser {\n"
    "                    Section {\n"
    "                        ScrollView(.horizontal, showsIndicators: false) {\n"
    "                            HStack(spacing: AppConstants.Spacing.sm) {\n"
    "                                iOSCategoryChip(\n"
    "                                    icon: \"tray.fill\",\n"
    "                                    name: \"None\",\n"
    "                                    color: AppConstants.Colors.textSecondary,\n"
    "                                    isSelected: selectedCategoryID == nil\n"
    "                                ) { selectedCategoryID = nil }\n"
    "                                ForEach(taskCategoryManager.categories) { cat in\n"
    "                                    iOSCategoryChip(\n"
    "                                        icon: cat.icon,\n"
    "                                        name: cat.name,\n"
    "                                        color: cat.color,\n"
    "                                        isSelected: selectedCategoryID == cat.id\n"
    "                                    ) { selectedCategoryID = cat.id }\n"
    "                                }\n"
    "                            }\n"
    "                            .padding(.vertical, 4)\n"
    "                        }\n"
    "                    } header: {\n"
    "                        Text(\"Category\")\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                // Priority\n"
    "                Section {\n"
    "                    Picker(\"Priority\", selection: $selectedPriority) {\n"
    "                        ForEach(Task.Priority.allCases, id: \\.self) { p in\n"
    "                            Text(p.rawValue).tag(p)\n"
    "                        }\n"
    "                    }\n"
    "                    .pickerStyle(.segmented)\n"
    "                } header: {\n"
    "                    Text(\"Priority\")\n"
    "                }\n"
    "\n"
    "                // Due Date\n"
    "                Section {\n"
    "                    Toggle(\"Set Due Date\", isOn: $hasDueDate)\n"
    "                        .tint(AppConstants.Colors.primaryAccent)\n"
    "                    if hasDueDate {\n"
    "                        DatePicker(\"Date\", selection: $dueDate, displayedComponents: [.date])\n"
    "                            .datePickerStyle(.compact)\n"
    "                    }\n"
    "                } header: {\n"
    "                    Text(\"Due Date\")\n"
    "                }\n"
    "\n"
    "                // Notes\n"
    "                Section {\n"
    "                    TextEditor(text: $notes)\n"
    "                        .font(.system(size: AppConstants.FontSize.body))\n"
    "                        .frame(minHeight: 80)\n"
    "                        .scrollContentBackground(.hidden)\n"
    "                } header: {\n"
    "                    Text(\"Notes (Optional)\")\n"
    "                }\n"
    "            }\n"
    "            .navigationTitle(\"Edit Task\")\n"
    "            .navigationBarTitleDisplayMode(.inline)\n"
    "            .toolbar {\n"
    "                ToolbarItem(placement: .cancellationAction) {\n"
    "                    Button(\"Cancel\") { dismiss() }\n"
    "                        .foregroundColor(AppConstants.Colors.textSecondary)\n"
    "                }\n"
    "                ToolbarItem(placement: .confirmationAction) {\n"
    "                    Button(\"Save\") {\n"
    "                        let trimmedTitle = taskTitle.trimmingCharacters(in: .whitespaces)\n"
    "                        let trimmedNotes = notes.trimmingCharacters(in: .whitespaces)\n"
    "                        var updated = task\n"
    "                        updated.title      = trimmedTitle\n"
    "                        updated.priority   = selectedPriority\n"
    "                        updated.dueDate    = hasDueDate ? dueDate : nil\n"
    "                        updated.notes      = trimmedNotes.isEmpty ? nil : trimmedNotes\n"
    "                        updated.categoryID = selectedCategoryID\n"
    "                        viewModel.updateTask(updated)\n"
    "                        dismiss()\n"
    "                    }\n"
    "                    .fontWeight(.semibold)\n"
    "                    .foregroundColor(AppConstants.Colors.primaryAccent)\n"
    "                    .disabled(taskTitle.trimmingCharacters(in: .whitespaces).isEmpty)\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}"
)

ok_edit = OLD_EDIT_BODY in tasks
print(f"iOSEditTaskSheet body found: {ok_edit}")
if ok_edit:
    tasks = tasks.replace(OLD_EDIT_BODY, NEW_EDIT_BODY)
    with open(tasks_path, "w") as f:
        f.write(tasks)
    print("iOSEditTaskSheet: OK")
else:
    idx = tasks.find("struct iOSEditTaskSheet")
    print(repr(tasks[idx:idx+300]))
    sys.exit(1)
